### ISSUE TITLE
Custom monocular pointclouds

### ISSUE THREAD

**Issue by VitorGuizilini-TRI** [xinzhuma/patchnet#3]
If I want to use my own monocular point clouds, instead of the ones you provide, what are the pre-processing steps required?

**Comment by xinzhuma** [comment]
> If I want to use my own monocular point clouds, instead of the ones you provide, what are the pre-processing steps required?

I think what you want to say is **depth map**, instead of **pseudo-LiDAR**. If you want to use your depth maps, note that:
- Please check the **resolution** of depth map, it should be consistent with that of corresponding image.
- Also note the **values** of depth map. For example, the values in provided depth map is 256x read values, so it should divided by 256 when we generate training data (Line 83, patch_data_prepare.py).
- Modify the **get_depth** function (in lib/dataset/kitti_dataset.py)  if your depth maps are not in **.png** format.
- Put them in the right **directory**.

**Comment by VitorGuizilini-TRI** [comment]
That makes sense, thanks!

**Comment by VitorGuizilini-TRI** [comment]
One more related question (I swear it's the last one): do you know how the DORN depth maps were produced? I mean, what sort of training data was used? I've seen some papers training the depth network on data that overlaps with the KITTI3D validation split, and that severely improves results.

**Comment by xinzhuma** [comment]
> One more related question (I swear it's the last one): do you know how the DORN depth maps were produced? I mean, what sort of training data was used? I've seen some papers training the depth network on data that overlaps with the KITTI3D validation split, and that severely improves results.

Yes, there is an overlap between DORN's training set and KITTI3D's val set. This problem should be taken seriously.
